package gcle;

import gcle.AjouterCoups.AjouterCoupsARetirer;
import gcle.AjouterCoups.AjouterCoupsDeplacement;
import gcle.AjouterCoups.AjouterCoupsNormal;
import gcle.AjouterCoups.AjouterCoupsPrise;
import gcle.AjouterCoups.AjouterCoupsRoque;
import gcle.AjouterCoups.AjouterPionEnPassant;
import gcle.AjouterCoups.AjouterPionPromotion;
import gcle.AjouterCoups.RetirerCoupsMiseEnEchec;
import gcle.IterateurClasse.CreerIterateurAileRoque;
import gcle.IterateurClasse.CreerIterateurAttaqueRoque;
import gcle.IterateurClasse.CreerIterateurFiltreEchec;
import gcle.IterateurClasse.CreerIterateurPosition;
import gcle.IterateurClasse.CreerIterateurPositionSimule;
import gcle.IterateurClasse.CreerIterateurPromotion;
import gcle.IterateurClasse.CreerIterateurSens;
import gcle.IterateurClasse.EstCaseDuRoi;
import gcle.IterateurClasse.ExisteAileSuivante;
import gcle.IterateurClasse.ExisteAttaqueRoqueSuivante;
import gcle.IterateurClasse.ExisteCoupsARetirerSuivant;
import gcle.IterateurClasse.ExisteCoupsPionSuivant;
import gcle.IterateurClasse.ExisteCoupsPromotionSuivant;
import gcle.IterateurClasse.ExistePieceSuivante;
import gcle.IterateurClasse.IterateurFiltreEchecs;
import gcle.IterateurClasse.SensSuivantPionPromotion;
import gcle.IterateurClasse.SuivantSens;
import gcle.IterateurClasse.SuivanteAileRoque;
import gcle.IterateurClasse.SuivanteCaseRoque;
import gcle.IterateurClasse.SuivantePiece;
import gcle.IterateurClasse.SuivantePiecePromotion;
import gcle.PFonction.CaseAJouer;
import gcle.PFonction.CaseDuRoi;
import gcle.PFonction.CaseSuivanteAvancePion;
import gcle.PFonction.CaseSuivanteDiagonalePion;
import gcle.PFonction.CaseSuivanteDirection;
import gcle.PFonction.CasesAttaqueRoque;
import gcle.PFonction.DeplacerPiece;
import gcle.PFonction.DeplacerPieceEnPassant;
import gcle.PFonction.DeplacerPiecePromotion;
import gcle.PFonction.EstAttaqueRoque;
import gcle.PFonction.EstPieceGlissante;
import gcle.PFonction.EstUnPion;
import gcle.PFonction.ExisteCase;
import gcle.PFonction.ExisteCaseEP;
import gcle.PFonction.FiltreEchec;
import gcle.PFonction.InitEstEnEchec;
import gcle.PFonction.InitFiltreEchec;
import gcle.PFonction.InitPseudoCoupsPion;
import gcle.PFonction.InitRoques;
import gcle.PFonction.InitSelonGlissant;
import gcle.PFonction.PieceAJouer;
import gcle.PFonction.PieceOpposante;
import gcle.PFonction.PionQuiALeTrait;
import gcle.PFonction.PoseRecherchePionAttaqueRoque;
import gcle.PFonction.PremiereCaseX;
import gcle.PFonction.PriseOuAttaque;
import gcle.PFonction.PseudoCoupsPion;
import gcle.PFonction.RangFinal;
import gcle.PFonction.RangInitial;
import gcle.PFonction.RoqueContexte;
import gcle.PFonction.RoquePossible;
import gcle.PFonction.RoquesEtat;
import gcle.PFonction.SimulePosition;
import gcle.PFonction.TypeDeplOuPrise;
import gcle.PFonction.TypeEnPassant;
import gcle.PFonction.TypePiece;
import gcle.PFonction.TypePromotion;
import gcle.PFonction.Vide;
import gcle.fonction.Fonction;

public class FonctionBase {
    public static final Fonction fCaseAJouer = new CaseAJouer();
    static final Fonction fPiecePromotionSuivante = new SuivantePiecePromotion();
    static final Fonction fCreerPositionIterateur = new CreerIterateurPosition();
    static final Fonction fPriseOuAttaque = new PriseOuAttaque();
    static final Fonction fAjouterCoups = new AjouterCoupsNormal();
    static final Fonction fCaseDuRoi = new CaseDuRoi();
    static final Fonction fInitFiltreEchec = new InitFiltreEchec();
    static final Fonction fSimulePosition = new SimulePosition();
    static final Fonction fRetirerCoupsMiseEnEchec = new RetirerCoupsMiseEnEchec();
    static final Fonction fInitEstEnEchec = new InitEstEnEchec();
    static final Fonction fDeplacerPiece = new DeplacerPiece();
    static final Fonction fVide = new Vide();
    static final Fonction fExisteCase = new ExisteCase();
    static final Fonction fRangFinal = new RangFinal();
    static final Fonction fRangInitial = new RangInitial();
    static final Fonction fPieceOpposante = new PieceOpposante();
    static final Fonction fPionQuiALeTrait = new PionQuiALeTrait();
    static final Fonction fTypePiece = new TypePiece();
    static final Fonction fAjouterCoupsPrise = new AjouterCoupsPrise();
    static final Fonction fAjouterCoupsDeplacement = new AjouterCoupsDeplacement();
    static final Fonction fAjouterPionPromotion = new AjouterPionPromotion();
    static final Fonction fAjouterPionEnPassant = new AjouterPionEnPassant();
    static final Fonction fAjouterCoupsRoque = new AjouterCoupsRoque();
    static final Fonction fPoseRecherchePionAttaqueRoque = new PoseRecherchePionAttaqueRoque();
    static final Fonction fPremiereCaseX = new PremiereCaseX();
    static final Fonction fPiecesAJouer = new PieceAJouer();
    static final Fonction fEstAttaqueRoque = new EstAttaqueRoque();
    static final Fonction fCaseSuivanteAvancePion = new CaseSuivanteAvancePion();
    static final Fonction fCaseSuivanteDiagonalePion = new CaseSuivanteDiagonalePion();
    static final Fonction fPieceSuivante = new SuivantePiece();
    static final Fonction fInitConditionRoque = new SuivanteAileRoque();
    static final Fonction fInitSelonGlissant = new InitSelonGlissant();
    static final Fonction fIterateurRoque = new SuivanteCaseRoque();
    static final Fonction fSensSuivantPionPromotion = new SensSuivantPionPromotion();
    static final Fonction fExisteCaseEP = new ExisteCaseEP();
    static final Fonction fRoqueContexte = new RoqueContexte();
    static final Fonction fRoquesEtat = new RoquesEtat();
    static final Fonction fConditionRoque = new ExisteAileSuivante();
    static final Fonction fRoquePossible = new RoquePossible();
    static final Fonction fExistePieceSuivante = new ExistePieceSuivante();
    static final Fonction fEstUnPion = new EstUnPion();
    static final Fonction fCaseSuivanteDirection = new CaseSuivanteDirection();
    static final Fonction fPseudoCoupsPion = new PseudoCoupsPion();
    static final Fonction fExisteCoupsPromotionSuivant = new ExisteCoupsPromotionSuivant();
    static final Fonction fCreerCoupsPromotionIterateur = new CreerIterateurPromotion();
    static final Fonction fSuivantRoque = new ExisteAttaqueRoqueSuivante();
    static final Fonction fCaseAttaqueRoque = new CasesAttaqueRoque();
    static final Fonction fExisteCoupsPionSuivant = new ExisteCoupsPionSuivant();
    static final Fonction fSensSuivant = new SuivantSens();
    static final Fonction fCreerCoupsPionIterateur = new CreerIterateurSens();
    static final Fonction fEstPieceGlissante = new EstPieceGlissante();
    static final Fonction fInitPseudoCoupsPion = new InitPseudoCoupsPion();
    static final Fonction fInitRoques = new InitRoques();
    static final Fonction fIterateurAileRoques = new CreerIterateurAileRoque();
    static final Fonction fIterateurAtaqueRoque = new CreerIterateurAttaqueRoque();
    static final Fonction fFiltreEchec = new FiltreEchec();
    static final Fonction fExisteCoupsARetirerSuivant = new ExisteCoupsARetirerSuivant();
    static final Fonction fAjouterCoupsARetirer = new AjouterCoupsARetirer();
    static final Fonction fIterateurFiltreEchecs = new IterateurFiltreEchecs();
    static final Fonction fEstCaseDuRoi = new EstCaseDuRoi();
    static final Fonction fTypeDeplOuPrise = new TypeDeplOuPrise();
    static final Fonction fTypeEnPassant = new TypeEnPassant();
    static final Fonction fTypePromotion = new TypePromotion();
    static final Fonction fDeplacerPieceEnPassant = new DeplacerPieceEnPassant();
    static final Fonction fDeplacerPiecePromotion = new DeplacerPiecePromotion();
    static final Fonction fCreerIterateurFiltreEchec = new CreerIterateurFiltreEchec();
    static final Fonction fCreerIterateurPositionSimule = new CreerIterateurPositionSimule();
}
